# Generated by Django 5.0.6 on 2024-05-28 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestion_equipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='es_personal',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='object_id',
        ),
        migrations.AddField(
            model_name='alumno',
            name='rut',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='asignado_a_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='asignado_a_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='equipo_reemplazo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rut',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('1ro básico', '1ro básico'), ('2do básico', '2do básico'), ('3ro básico', '3ro básico'), ('4to básico', '4to básico'), ('5to básico', '5to básico'), ('6to básico', '6to básico'), ('7mo básico', '7mo básico'), ('8vo básico', '8vo básico'), ('1ro medio', '1ro medio'), ('2do medio', '2do medio'), ('3ro medio', '3ro medio'), ('4to medio', '4to medio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(choices=[('1-A', '1-A'), ('1-B', '1-B'), ('2-A', '2-A'), ('2-B', '2-B'), ('3-A', '3-A'), ('3-B', '3-B'), ('4-A', '4-A'), ('4-B', '4-B'), ('5-A', '5-A'), ('5-B', '5-B'), ('6-A', '6-A'), ('6-B', '6-B'), ('7-A', '7-A'), ('7-B', '7-B'), ('8-A', '8-A'), ('8-B', '8-B'), ('9-A', '9-A'), ('9-B', '9-B'), ('10-A', '10-A'), ('10-B', '10-B'), ('11-A', '11-A'), ('11-B', '11-B'), ('12-A', '12-A'), ('12-B', '12-B')], max_length=5),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamientos', to='gestion_equipos.ubicacion'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='codigo',
            field=models.CharField(choices=[('CH', 'Chicureo'), ('LB', 'Lo Barnechea')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
